/* eslint-disable @next/next/no-html-link-for-pages -- Cached pages use full-page navigation offline. */
"use client";
import PageHeader from "../PageHeader";
import {useEffect,useRef,useState} from "react";
import {districts,adjacent,target,type Clue} from "./world";
import {trackMetric} from "../analytics/events";
type Note=Clue|{name:string;title:string;text:string;source?:string};
function Spark({small=false}:{small?:boolean}){return <svg viewBox="0 0 80 80" aria-hidden="true" className={small?"pw-spark small":"pw-spark"}><path d="M40 3 48 27 73 40 48 51 40 77 31 52 7 40 31 28Z" fill="currentColor"/><circle cx="34" cy="39" r="3" fill="#152638"/><circle cx="47" cy="39" r="3" fill="#152638"/><path d="M35 48Q40 52 46 47" fill="none" stroke="#152638" strokeWidth="3" strokeLinecap="round"/></svg>;}
export default function LightTrail(){
 const [started,setStarted]=useState(false),[level,setLevel]=useState(0),[position,setPosition]=useState(28),[found,setFound]=useState<number[]>([]),[cleared,setCleared]=useState<number[]>([]),[note,setNote]=useState<Note|null>(null),[status,setStatus]=useState(""),[finished,setFinished]=useState(false),[moves,setMoves]=useState(0);
 const board=useRef<HTMLDivElement>(null),noteHeading=useRef<HTMLHeadingElement>(null),startButton=useRef<HTMLButtonElement>(null);
 const district=districts[level];const light=found.length;
 useEffect(()=>{if(note)noteHeading.current?.focus();},[note]);
 function begin(){setStarted(true);setFinished(false);setLevel(0);setPosition(28);setFound([]);setCleared([]);setNote(null);setMoves(0);setStatus("เดินหาแสงทั้ง 3 จุด แล้วไปที่ประตูดาว");trackMetric("puff_start");}
 function move(to:number){
  if(!started||finished||note||to===position)return;
  if(!adjacent(position,to)){setStatus("แตะช่องข้างตัวคุณ หรือใช้ปุ่มลูกศรเพื่อเดิน");return;}
  if(district.walls.includes(to)){setStatus("อาคารอยู่ตรงนี้ ลองเดินอ้อมไปทางอื่น");return;}
  setPosition(to);setMoves(value=>value+1);
  const clue=district.clues.find(item=>item.at===to);
  if(clue&&!found.includes(to)){setFound(previous=>[...previous,to]);setNote(clue);setStatus(`พบ ${clue.name}`);trackMetric("puff_clue",{scene:level+1,choice:district.clues.indexOf(clue)});return;}
  if(district.fog.includes(to)&&!cleared.includes(to)){setCleared(previous=>[...previous,to]);setNote({name:"เสียงจากหมอก",title:"หยุด เช็ก แล้วค่อยเชื่อ",text:"ในโลกนี้ หมอกแทนข้อความชวนเชื่อ ไม่ใช่ภาพจำลองสุขภาพ ยิ่งคุณถามหาหลักฐาน คุณยิ่งเห็นทางของตัวเองชัดขึ้น"});return;}
  if(to===district.exit){if(found.length<3){setStatus(`ประตูยังไม่เปิด หาแสงอีก ${3-found.length} จุด`);return;}if(level===2){setFinished(true);trackMetric("puff_complete");setStatus("คุณนำแสงกลับมาครบทั้งสามเมืองแล้ว");}else{setLevel(value=>value+1);setPosition(28);setFound([]);setCleared([]);setStatus(`เดินทางถึง ${districts[level+1].name} หาแสงทั้ง 3 จุด`);}return;}
  setStatus(`คุณอยู่แถว ${Math.floor(to/7)+1} ช่อง ${to%7+1} · แสง ${found.length}/3`);
 }
 function closeNote(){setNote(null);requestAnimationFrame(()=>board.current?.focus());}
 function key(event:React.KeyboardEvent){const direction:Record<string,[number,number]>={ArrowUp:[0,-1],w:[0,-1],ArrowDown:[0,1],s:[0,1],ArrowLeft:[-1,0],a:[-1,0],ArrowRight:[1,0],d:[1,0]};const delta=direction[event.key];if(delta){event.preventDefault();move(target(position,...delta));}}
 return <div className="pw-page" style={{"--pw-accent":district.color} as React.CSSProperties}><PageHeader />
 {!started?<main className="pw-intro"><div className="pw-intro-copy"><h1>Light<br/><span>Trail.</span></h1><p className="pw-lede">ตามหาแสง แล้วเปิดทางให้เมือง</p><button ref={startButton} className="pw-primary" onClick={begin}>ออกเดินทาง <span>↗</span></button><p className="pw-small">ลูกศร / WASD · แตะช่องข้างตัว</p></div><div className="pw-poster" aria-hidden="true"><div className="pw-orbit orbit-one"/><div className="pw-orbit orbit-two"/><div className="pw-floating-city"><div className="pw-tower tower-one"/><div className="pw-tower tower-two"/><div className="pw-tower tower-three"/><div className="pw-tower tower-four"/><div className="pw-cloud cloud-one"/><div className="pw-cloud cloud-two"/><Spark/><div className="pw-poster-label">FOLLOW THE LIGHT</div></div><span className="pw-coordinate">13°N / YOUR NEXT CHOICE</span></div></main>
 :finished?<main className="pw-finish"><div className="pw-finish-art" aria-hidden="true"><Spark/><span>✦</span><span>✦</span><span>✦</span></div><h1>เมืองสว่างขึ้น<br/><span>เมื่อคุณรู้ทัน</span></h1><p className="pw-lede">คุณสำรวจครบ 9 เบาะแส ใน {moves} ก้าว</p><div className="pw-takeaways"><article><h2>มองผ่านบรรจุภัณฑ์</h2><p>รส สี และความน่ารักไม่ได้ยืนยันความปลอดภัย</p></article><article><h2>ถามว่าสูดอะไร</h2><p>ละอองไม่ใช่แค่ไอน้ำ ตรวจสอบจากแหล่งข้อมูลที่เชื่อถือได้</p></article><article><h2>เลือกและช่วยกันได้</h2><p>ตั้งขอบเขต รับฟัง และหาคนให้คำปรึกษาเมื่ออยากเลิก</p></article></div><div className="pw-finish-actions"><a className="pw-primary" href="/#community">เขียนคำตอบในแบบคุณ ↗</a><button className="pw-secondary" onClick={begin}>สำรวจอีกครั้ง</button></div><p className="pw-small">แสงและจำนวนก้าวเป็นกลไกของเกม ไม่ใช่คะแนนสุขภาพหรือผลวัดการเรียนรู้</p></main>
 :<main className="pw-game"><div className="pw-game-top"><div><p className="pw-kicker">DISTRICT {String(level+1).padStart(2,"0")} / 03</p><h1>{district.name}</h1><p>{district.thai}</p></div><div className="pw-lights" aria-label={`พบแสง ${light} จาก 3 จุด`}>{[0,1,2].map(i=><span className={i<light?"lit":""} key={i}>✦</span>)}</div></div><div className="pw-game-layout"><section className={`pw-scene light-${light}`} aria-label="แผนที่เมือง"><div className="pw-scene-title"><span>เดินหาแสง → เปิดประตูดาว</span><span>{moves} ก้าว</span></div><div className="pw-board" ref={board} tabIndex={0} onKeyDown={key} aria-label="แผนที่ 5 แถว 7 ช่อง ใช้ลูกศรหรือ WASD เดิน">{Array.from({length:35},(_,at)=>{const wall=district.walls.includes(at),clue=district.clues.find(c=>c.at===at),fog=district.fog.includes(at)&&!cleared.includes(at),collected=found.includes(at),exit=at===district.exit,player=at===position;return <button key={at} tabIndex={player?0:-1} onClick={()=>move(at)} className={`pw-tile ${wall?"building":"road"} ${fog?"fog":""} ${clue&&!collected?"beacon":""} ${exit?"exit":""} ${player?"player":""}`} aria-label={`แถว ${Math.floor(at/7)+1} ช่อง ${at%7+1}: ${player?"คุณอยู่ที่นี่":wall?"อาคาร":clue&&!collected?clue.name:exit?light===3?"ประตูเปิด":"ประตูยังปิด":fog?"หมอกชวนเชื่อ":collected?"พบเบาะแสแล้ว":"ทางเดิน"}`}><span aria-hidden="true">{player?<Spark small/>:wall?<i className="pw-building"/>:clue&&!collected?<span className="pw-beacon">✦</span>:exit?<span className={light===3?"pw-gate open":"pw-gate"}>☆</span>:fog?<span className="pw-mist">☁</span>:collected?<span className="pw-found">·</span>:null}</span></button>;})}</div><div className="pw-legend"><span>✦ เบาะแส</span><span>☁ ข้อความชวนเชื่อ</span><span>☆ ประตูเมือง</span></div></section><aside className="pw-side"><h2>แสงที่คุณพบ</h2><ol>{district.clues.map((clue,index)=><li key={clue.at} className={found.includes(clue.at)?"found":""}><span>{found.includes(clue.at)?"✓":`0${index+1}`}</span><div><b>{clue.name}</b>{found.includes(clue.at)&&<button onClick={()=>setNote(clue)}>อ่านเบาะแสอีกครั้ง ↗</button>}</div></li>)}</ol><p className="pw-status" role="status">{status}</p><div className="pw-dpad" aria-label="ปุ่มเดิน"><button className="up" aria-label="เดินขึ้น" onClick={()=>move(target(position,0,-1))}>↑</button><button className="left" aria-label="เดินซ้าย" onClick={()=>move(target(position,-1,0))}>←</button><span><Spark small/></span><button className="right" aria-label="เดินขวา" onClick={()=>move(target(position,1,0))}>→</button><button className="down" aria-label="เดินลง" onClick={()=>move(target(position,0,1))}>↓</button></div><p className="pw-small">ลูกศร / WASD · แตะช่องข้างตัว<br/>ไม่มีเวลาและไม่มีทางเลือกให้สูบ</p><button className="pw-restart" onClick={()=>{setStarted(false);requestAnimationFrame(()=>startButton.current?.focus());}}>กลับหน้าเริ่มเกม</button></aside></div></main>}
 {note&&<div className="pw-note-backdrop"><section role="dialog" aria-modal="true" aria-labelledby="pw-note-title" className="pw-note" onKeyDown={event=>{if(event.key==="Escape")closeNote();if(event.key==="Tab"){const controls=Array.from(event.currentTarget.querySelectorAll<HTMLElement>('a,button'));const first=controls[0],last=controls[controls.length-1];if(event.shiftKey&&(document.activeElement===first||document.activeElement===noteHeading.current)){event.preventDefault();last?.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first?.focus();}}}}><p className="pw-kicker">{note.name}</p><div className="pw-note-spark" aria-hidden="true"><Spark/></div><h2 id="pw-note-title" tabIndex={-1} ref={noteHeading}>{note.title}</h2><p>{note.text}</p>{note.source&&<a href={note.source} target={note.source.startsWith('http')?'_blank':undefined} rel="noreferrer">อ่านแหล่งข้อมูล ↗</a>}<button className="pw-primary" onClick={closeNote}>เก็บแสง แล้วเดินต่อ →</button></section></div>}
 <footer className="pw-footer"><span>โลกสมมติเพื่อการเรียนรู้ · RE;light</span><a href="/#sources-title">แหล่งข้อมูล ↗</a></footer></div>;
}
